In [1]:
import pandas as pd

data = pd.read_csv('Data/Processed/general_data.csv')

In [ ]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7048 entries, 0 to 7047
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Start_Time   7048 non-null   str
 1   Size(MB)     7048 non-null   float64
 2   SkillID      7048 non-null   str
 3   Operator     7048 non-null   str
 4   BagName      7048 non-null   str
 5   Duration(s)  7048 non-null   float64
 6   Station      7048 non-null   str
 7   IsValid      7048 non-null   bool
 8   SkillName    7048 non-null   str
dtypes: bool(1), float64(2), str(6)
memory usage: 1.0 MB

In [ ]:
data[data['IsValid']==True]

,Start_Time,Size(MB),SkillID,Operator,BagName,Duration(s),Station,IsValid,SkillName
0,2026-01-30T09:41:14Z,2612.05,SKILL_017,d_vargas,SKILL_017_20260130_094114,543.35,1,True,Put pasta in ziploc bags
2,2026-01-30T09:57:36Z,948.96,SKILL_018,d_vargas,SKILL_018_20260130_095736,209.58,1,True,Close bags with twist ties
3,2026-01-30T09:52:37Z,923.89,SKILL_018,d_vargas,SKILL_018_20260130_095237,199.90,1,True,Close bags with twist ties
5,2026-01-30T10:02:15Z,608.43,SKILL_018,d_vargas,SKILL_018_20260130_100215,140.53,1,True,Close bags with twist ties
6,2026-02-02T14:06:16Z,8252.25,SKILL_003,d_vargas,SKILL_003_20260202_140616,228.19,2,True,Organize screwdriver bits
...,...,...,...,...,...,...,...,...,...
7031,2026-02-18T07:41:55Z,5777.67,SKILL_023,e_cabezas,SKILL_023_20260218_074155,610.45,03,True,Built up box (Present)
7037,2026-02-18T10:28:47Z,2117.07,SKILL_024,e_martinez,SKILL_024_20260218_102847,216.63,04,True,Put hooks on shower courtain
7038,2026-02-18T09:54:58Z,2627.87,SKILL_013,e_martinez,SKILL_013_20260218_095458,268.83,04,True,Set up a hand lamp
7042,2026-02-18T07:44:51Z,2406.93,SKILL_014,l_aguilera,SKILL_014_20260218_074451,228.75,04,True,Fasten nuts onto bolts
7046,2026-02-18T10:34:57Z,2763.13,SKILL_024,e_martinez,SKILL_024_20260218_103457,273.31,04,True,Put hooks on shower courtain

In [ ]:
data[data['IsValid']==False]

,Start_Time,Size(MB),SkillID,Operator,BagName,Duration(s),Station,IsValid,SkillName
1,2026-01-30T10:34:15Z,181.49,SKILL_021,d_vargas,SKILL_021_20260130_103415,24.14,1,False,Build Up Box (Mailer)
4,2026-01-30T10:48:08Z,28.47,SKILL_022,d_vargas,SKILL_022_20260130_104808,4.07,1,False,Build Up Box (Regular ECT)
7,2026-01-30T10:45:58Z,378.33,SKILL_022,d_vargas,SKILL_022_20260130_104558,45.37,1,False,Build Up Box (Regular ECT)
8,2026-01-30T10:56:16Z,434.53,SKILL_023,d_vargas,SKILL_023_20260130_105616,89.45,1,False,Built up box (Present)
16,2026-01-30T10:42:15Z,352.19,SKILL_022,d_vargas,SKILL_022_20260130_104215,75.10,1,False,Build Up Box (Regular ECT)
...,...,...,...,...,...,...,...,...,...
7041,2026-02-18T10:16:48Z,733.23,SKILL_040,e_martinez,SKILL_040_20260218_101648,101.51,04,False,Fasten a belt
7043,2026-02-18T12:30:48Z,1499.30,SKILL_004,l_aguilera,SKILL_004_20260218_123048,150.92,04,False,Set Screwdriver package
7044,2026-02-18T14:06:44Z,3611.61,SKILL_003,e_martinez,SKILL_003_20260218_140644,479.90,04,False,Organize screwdriver bits
7045,2026-02-18T14:17:11Z,3127.85,SKILL_014,e_martinez,SKILL_014_20260218_141711,335.53,04,False,Fasten nuts onto bolts
7047,2026-02-18T10:08:19Z,2683.89,SKILL_012,e_martinez,SKILL_012_20260218_100819,321.80,04,False,Put pasta in jars

In [ ]:
p = list(data['Operator'].unique())

In [ ]:
p

['d_vargas',
 'c_becerra',
 'n_mora',
 'l_aguilera',
 'e_martinez',
 'a_rodriguez',
 'JUAN',
 'Juan',
 'juan',
 'C_BECERRA',
 'C_becerra',
 'h_alcaraz',
 'D_vargas',
 'H_alcaraz',
 'N_mora',
 'N_MORA',
 'H_ALCARAZ',
 'D_VARGAS',
 'L_AGUILERA',
 'E_MARTINEZ',
 'e_cabezas']

In [ ]:
p.insert(0,None)

In [ ]:
print(p)

[None, 'd_vargas', 'c_becerra', 'n_mora', 'l_aguilera', 'e_martinez', 'a_rodriguez', 'JUAN', 'Juan', 'juan', 'C_BECERRA', 'C_becerra', 'h_alcaraz', 'D_vargas', 'H_alcaraz', 'N_mora', 'N_MORA', 'H_ALCARAZ', 'D_VARGAS', 'L_AGUILERA', 'E_MARTINEZ', 'e_cabezas', None]

In [ ]:
opes = list(data['Operator'].unique())

In [ ]:
import pandas as pd
data = pd.read_csv('Data/Raw/nurvai_stage_recordings.csv')

/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_38799/1111878981.py:2: DtypeWarning: Columns (0: metadata.technical_report.topics./camera_l/color/image_rect_raw/compressed.encoding, 1: metadata.technical_report.topics./camera_r/color/image_rect_raw/compressed.encoding, 2: metadata.technical_report.topics./camera_r/aligned_depth_to_color/camera_info.encoding, 3: metadata.technical_report.topics./camera_l/aligned_depth_to_color/camera_info.encoding, 4: metadata.version, 5: metadata.basic_info.station_id, 6: station_id, 7: metadata.technical_report.topics./nurvai01/camera_l/color/image_rect_raw/compressed.encoding, 8: metadata.technical_report.topics./nurvai01/camera_r/color/image_rect_raw/compressed.encoding, 9: metadata.technical_report.topics./nurvai01/gripper_l/data.encoding, 10: metadata.technical_report.topics./nurvai01/gripper_r/data.encoding, 11: metadata.technical_report.topics./camera_l/depth/image_rect_raw/compressed.encoding, 12: metadata.technical_report.topics./camera_r/extrinsics/depth_to_color.encoding, 13: metadata.technical_report.topics./camera_fisheye_l/color/image_raw.encoding, 14: metadata.technical_report.topics./camera_l/depth/metadata.encoding, 15: metadata.technical_report.topics./camera_r/color/image_rect_raw.encoding, 16: metadata.technical_report.topics./camera_r/depth/metadata.encoding, 17: metadata.technical_report.topics./rosout.encoding, 18: metadata.technical_report.topics./camera_r/depth/image_rect_raw/compressed.encoding, 19: metadata.technical_report.topics./gripper_l/joint_state.encoding, 20: metadata.technical_report.topics./camera_l/color/metadata.encoding, 21: metadata.technical_report.topics./camera_l/extrinsics/depth_to_color.encoding, 22: metadata.technical_report.topics./camera_r/color/metadata.encoding, 23: metadata.technical_report.topics./camera_l/color/image_rect_raw.encoding, 24: metadata.technical_report.topics./gripper_r/joint_state.encoding, 25: metadata.technical_report.topics./pika_localization_status_h.encoding, 26: metadata.technical_report.topics./nurvai02/camera_l/color/image_rect_raw/compressed.encoding, 27: metadata.technical_report.topics./nurvai02/camera_r/color/image_rect_raw/compressed.encoding, 28: metadata.technical_report.topics./nurvai02/gripper_l/data.encoding, 29: metadata.technical_report.topics./nurvai02/gripper_r/data.encoding, 30: metadata.technical_report.topics./nurvai01/camera_fisheye_l/color/image_raw.encoding, 31: metadata.technical_report.topics./nurvai01/camera_l/color/camera_info.encoding, 32: metadata.technical_report.topics./nurvai01/camera_l/color/metadata.encoding, 33: metadata.technical_report.topics./nurvai01/camera_l/color/image_rect_raw.encoding, 34: metadata.technical_report.topics./nurvai01/camera_r/depth/image_rect_raw.encoding, 35: metadata.technical_report.topics./nurvai01/camera_l/depth/camera_info.encoding, 36: metadata.technical_report.topics./nurvai01/camera_l/depth/image_rect_raw.encoding, 37: metadata.technical_report.topics./nurvai01/camera_l/depth/image_rect_raw/compressed.encoding, 38: metadata.technical_report.topics./nurvai01/gripper_r/joint_state.encoding, 39: metadata.technical_report.topics./nurvai01/camera_fisheye_l/color/camera_info.encoding, 40: metadata.technical_report.topics./nurvai01/camera_fisheye_r/color/camera_info.encoding, 41: metadata.technical_report.topics./nurvai01/camera_l/extrinsics/depth_to_color.encoding, 42: metadata.technical_report.topics./camera_fisheye_r/color/image_raw.encoding, 43: metadata.technical_report.topics./parameter_events.encoding, 44: metadata.technical_report.topics./camera_l/extrinsics/depth_to_depth.encoding, 45: metadata.technical_report.topics./camera_r/aligned_depth_to_color/image_raw/compressed.encoding, 46: metadata.technical_report.topics./camera_l/aligned_depth_to_color/image_raw/compressed.encoding, 47: metadata.technical_report.topics./pika_pose_h.encoding, 48: metadata.technical_report.topics./pika_pose_l.status, 49: metadata.technical_report.topics./camera_r/color/camera_info.status, 50: metadata.technical_report.topics./camera_r/depth/image_rect_raw.status, 51: metadata.technical_report.topics./gripper_r/data.status, 52: metadata.technical_report.topics./pika_pose_h.status, 53: metadata.technical_report.topics./pika_pose_r.status, 54: metadata.technical_report.topics./tf_static.status, 55: metadata.technical_report.topics./camera_fisheye_r/color/camera_info.status, 56: metadata.technical_report.topics./camera_l/color/camera_info.status, 57: metadata.technical_report.topics./camera_r/depth/camera_info.status, 58: metadata.technical_report.topics./tf.status, 59: metadata.technical_report.topics./camera_fisheye_l/color/camera_info.status, 60: metadata.technical_report.topics./camera_fisheye_r/ffmpeg.status, 61: metadata.technical_report.topics./camera_l/depth/camera_info.status, 62: metadata.technical_report.topics./camera_l/depth/image_rect_raw.status, 63: metadata.technical_report.topics./camera_r/ffmpeg.status, 64: metadata.technical_report.topics./camera_fisheye_l/ffmpeg.status, 65: metadata.technical_report.topics./camera_l/ffmpeg.status, 66: metadata.technical_report.topics./gripper_l/data.status) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('Data/Raw/nurvai_stage_recordings.csv')

In [ ]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8833 entries, 0 to 8832
Columns: 339 entries, _id to metadata.technical_report.topics./gripper_l/data.status
dtypes: bool(1), float64(212), int64(1), object(2), str(123)
memory usage: 28.9+ MB

In [ ]:
data.iloc[:,1:11]

,bag_name,duration_sec,ingested_at,metadata.task_context.skill_code,metadata.task_context.skill_id,metadata.task_context.skill_name,metadata.task_context.operator_code,metadata.task_context.operator_id,metadata.technical_report.quality_gate.is_valid,metadata.technical_report.quality_gate.reason
0,SKILL_017_20260130_094114,542.804108,2026-02-23T05:22:14.495Z,SKILL_017,699bd8c722f7b8d2f943dd7d,Put pasta in ziploc bags,d_vargas,699bd8dd22f7b8d2f943dd97,False,MISSING_CRIT /camera_fisheye_r/ffmpeg | MISSIN...
1,SKILL_018_20260130_095237,199.397428,2026-02-23T05:22:04.040Z,SKILL_018,699bd8c722f7b8d2f943dd7e,Close bags with twist ties,d_vargas,699bd8dd22f7b8d2f943dd97,False,MISSING_CRIT /camera_l/ffmpeg | MISSING_CRIT /...
2,SKILL_018_20260130_095736,208.702662,2026-02-23T05:38:34.906Z,SKILL_018,699bd8c722f7b8d2f943dd7e,Close bags with twist ties,d_vargas,699bd8dd22f7b8d2f943dd97,False,BAD_HZ /gripper_l/data (98.2/120.0) | MISSING_...
3,SKILL_018_20260130_100215,140.026791,2026-02-23T05:38:35.855Z,SKILL_018,699bd8c722f7b8d2f943dd7e,Close bags with twist ties,d_vargas,699bd8dd22f7b8d2f943dd97,False,MISSING_CRIT /camera_fisheye_l/ffmpeg | MISSIN...
4,SKILL_019_20260130_101354,174.669831,2026-02-23T05:38:36.830Z,SKILL_019,699bd8c722f7b8d2f943dd7f,Put pasta in plastic containers,d_vargas,699bd8dd22f7b8d2f943dd97,False,MISSING_CRIT /camera_fisheye_l/ffmpeg | MISSIN...
...,...,...,...,...,...,...,...,...,...,...
8828,SKILL_042_20260303_085820,50.946379,2026-03-03T14:59:30.248Z,SKILL_042,69a59a70e1efd2d8835b6b15,Put crystal tubes on their holder and stuff th...,l_aguilera,699bd8dd22f7b8d2f943dd99,False,TOO_SHORT (50.9s < 90.0s)
8829,SKILL_017_20260303_084921,605.938992,2026-03-03T15:00:44.661Z,SKILL_017,699bd8c722f7b8d2f943dd7d,Put pasta in ziploc bags,d_vargas,699bd8dd22f7b8d2f943dd97,True,NaN
8830,SKILL_018_20260303_090540,255.516448,2026-03-03T15:10:30.811Z,SKILL_018,699bd8c722f7b8d2f943dd7e,Close bags with twist ties,c_becerra,699bd8dd22f7b8d2f943dd96,True,NaN
8831,SKILL_018_20260303_091043,96.995837,2026-03-03T15:12:41.519Z,SKILL_018,699bd8c722f7b8d2f943dd7e,Close bags with twist ties,c_becerra,699bd8dd22f7b8d2f943dd96,True,NaN
8832,SKILL_042_20260303_090611,600.092522,2026-03-03T15:17:30.749Z,SKILL_042,69a59a70e1efd2d8835b6b15,Put crystal tubes on their holder and stuff th...,e_cabezas,699bd8dd22f7b8d2f943dd9b,True,NaN

In [13]:
data.iloc[:,11:22]

,metadata.technical_report.quality_gate.evaluated_at,metadata.technical_report.storage.avg_write_mbps,metadata.technical_report.storage.mcap_size_bytes,metadata.technical_report.time_analysis.drift_sec,metadata.technical_report.time_analysis.json_duration_sec,metadata.technical_report.time_analysis.mcap_duration_sec,metadata.technical_report.topics./camera_l/color/camera_info.data_volume_bytes,metadata.technical_report.topics./camera_l/color/camera_info.encoding,metadata.technical_report.topics./camera_l/color/camera_info.frequency_avg_hz,metadata.technical_report.topics./camera_l/color/camera_info.message_count,metadata.technical_report.topics./camera_l/color/image_rect_raw/compressed.data_volume_bytes
0,2026-02-22T23:22:14-06:00,4.812139,2738931573,0.544475,543.348583,542.804108,0.0,cdr,29.657108,16098.0,0.0
1,2026-02-22T23:22:03-06:00,4.633418,968770547,0.500838,199.898266,199.397428,0.0,cdr,29.839903,5950.0,0.0
2,2026-02-22T23:38:34-06:00,4.546970,995061639,0.875459,209.578121,208.702662,0.0,cdr,29.990034,6259.0,0.0
3,2026-02-22T23:38:35-06:00,4.345095,637984834,0.498739,140.525530,140.026791,0.0,cdr,29.987119,4199.0,0.0
4,2026-02-22T23:38:36-06:00,5.015954,918694939,0.482606,175.152437,174.669831,0.0,cdr,29.993732,5239.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
8828,2026-03-03T14:59:30Z,11.161207,596244534,0.466052,51.412431,50.946379,0.0,unknown,29.874547,1522.0,NaN
8829,2026-03-03T15:00:44Z,10.470850,6652896046,0.747658,606.686650,605.938992,0.0,unknown,29.993118,18174.0,NaN
8830,2026-03-03T15:10:30Z,7.975893,2136968452,0.354434,255.870882,255.516448,0.0,unknown,29.982414,7661.0,NaN
8831,2026-03-03T15:12:41Z,7.931327,806675496,0.354948,97.350785,96.995837,0.0,unknown,29.691996,2880.0,NaN
8832,2026-03-03T15:17:30Z,10.578747,6656598656,0.497156,600.589678,600.092522,0.0,unknown,29.980377,17991.0,NaN

In [11]:
data.shape

(8833, 339)

In [14]:
data.iloc[:,22:33]

,metadata.technical_report.topics./camera_l/color/image_rect_raw/compressed.encoding,metadata.technical_report.topics./camera_l/color/image_rect_raw/compressed.frequency_avg_hz,metadata.technical_report.topics./camera_l/color/image_rect_raw/compressed.message_count,metadata.technical_report.topics./camera_r/color/image_rect_raw/compressed.frequency_avg_hz,metadata.technical_report.topics./camera_r/color/image_rect_raw/compressed.message_count,metadata.technical_report.topics./camera_r/color/image_rect_raw/compressed.data_volume_bytes,metadata.technical_report.topics./camera_r/color/image_rect_raw/compressed.encoding,metadata.technical_report.topics./gripper_l/data.data_volume_bytes,metadata.technical_report.topics./gripper_l/data.encoding,metadata.technical_report.topics./gripper_l/data.frequency_avg_hz,metadata.technical_report.topics./gripper_l/data.message_count
0,cdr,29.657108,16098.0,29.994246,16281.0,0.0,cdr,0.0,cdr,116.752985,63374.0
1,cdr,29.844919,5951.0,29.995372,5981.0,0.0,cdr,0.0,cdr,118.953390,23719.0
2,cdr,29.994826,6260.0,29.994826,6260.0,0.0,cdr,0.0,cdr,98.206701,20496.0
3,cdr,29.994260,4200.0,29.994260,4200.0,0.0,cdr,0.0,cdr,118.777270,16632.0
4,cdr,29.999457,5240.0,29.999457,5240.0,0.0,cdr,0.0,cdr,116.791778,20400.0
...,...,...,...,...,...,...,...,...,...,...,...
8828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,unknown,111.509397,5681.0
8829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,unknown,116.128853,70367.0
8830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,unknown,116.673507,29812.0
8831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,unknown,116.345200,11285.0
8832,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,unknown,116.295400,69788.0

In [ ]:
data.iloc[:,33:44]

,metadata.technical_report.topics./gripper_r/data.encoding,metadata.technical_report.topics./gripper_r/data.frequency_avg_hz,metadata.technical_report.topics./gripper_r/data.message_count,metadata.technical_report.topics./gripper_r/data.data_volume_bytes,metadata.technical_report.topics./pika_pose_r.data_volume_bytes,metadata.technical_report.topics./pika_pose_r.encoding,metadata.technical_report.topics./pika_pose_r.frequency_avg_hz,metadata.technical_report.topics./pika_pose_r.message_count,metadata.technical_report.topics./camera_r/aligned_depth_to_color/camera_info.message_count,metadata.technical_report.topics./camera_r/aligned_depth_to_color/camera_info.data_volume_bytes,metadata.technical_report.topics./camera_r/aligned_depth_to_color/camera_info.encoding
0,cdr,116.209511,63079.0,0.0,0.0,cdr,100.001085,54281.0,16281.0,0.0,cdr
1,cdr,116.205110,23171.0,0.0,0.0,cdr,99.981229,19936.0,5980.0,0.0,cdr
2,cdr,125.000801,26088.0,0.0,0.0,cdr,100.003516,20871.0,6260.0,0.0,cdr
3,cdr,111.000187,15543.0,0.0,0.0,cdr,99.973725,13999.0,4199.0,0.0,cdr
4,cdr,117.146733,20462.0,0.0,0.0,cdr,99.112709,17312.0,5239.0,0.0,cdr
...,...,...,...,...,...,...,...,...,...,...,...
8828,unknown,109.958747,5602.0,0.0,0.0,unknown,98.103145,4998.0,NaN,NaN,NaN
8829,unknown,116.511730,70599.0,0.0,0.0,unknown,100.001817,60595.0,NaN,NaN,NaN
8830,unknown,116.305624,29718.0,0.0,0.0,unknown,99.958340,25541.0,NaN,NaN,NaN
8831,unknown,114.551308,11111.0,0.0,0.0,unknown,98.993940,9602.0,NaN,NaN,NaN
8832,unknown,115.978782,69598.0,0.0,0.0,unknown,99.999580,60009.0,NaN,NaN,NaN

In [16]:
data.iloc[:,44:55]

,metadata.technical_report.topics./camera_r/aligned_depth_to_color/camera_info.frequency_avg_hz,metadata.technical_report.topics./camera_r/color/camera_info.data_volume_bytes,metadata.technical_report.topics./camera_r/color/camera_info.encoding,metadata.technical_report.topics./camera_r/color/camera_info.frequency_avg_hz,metadata.technical_report.topics./camera_r/color/camera_info.message_count,metadata.technical_report.topics./pika_pose_l.data_volume_bytes,metadata.technical_report.topics./pika_pose_l.encoding,metadata.technical_report.topics./pika_pose_l.frequency_avg_hz,metadata.technical_report.topics./pika_pose_l.message_count,metadata.technical_report.topics./camera_fisheye_r/color/camera_info.data_volume_bytes,metadata.technical_report.topics./camera_fisheye_r/color/camera_info.encoding
0,29.994246,0.0,cdr,29.994246,16281.0,0.0,cdr,100.001085,54281.0,0.0,cdr
1,29.990357,0.0,cdr,29.990357,5980.0,0.0,cdr,99.986244,19937.0,0.0,cdr
2,29.994826,0.0,cdr,29.994826,6260.0,0.0,cdr,99.208126,20705.0,0.0,cdr
3,29.987119,0.0,cdr,29.994260,4200.0,0.0,cdr,95.053238,13310.0,0.0,cdr
4,29.993732,0.0,cdr,29.993732,5239.0,0.0,cdr,99.662317,17408.0,0.0,cdr
...,...,...,...,...,...,...,...,...,...,...,...
8828,NaN,0.0,unknown,29.992318,1528.0,0.0,unknown,98.103145,4998.0,0.0,unknown
8829,NaN,0.0,unknown,29.971664,18161.0,0.0,unknown,100.001817,60595.0,0.0,unknown
8830,NaN,0.0,unknown,29.982414,7661.0,0.0,unknown,99.962254,25542.0,0.0,unknown
8831,NaN,0.0,unknown,29.990978,2909.0,0.0,unknown,98.993940,9602.0,0.0,unknown
8832,NaN,0.0,unknown,29.990375,17997.0,0.0,unknown,99.999580,60009.0,0.0,unknown

In [19]:
print(data.columns)

Index(['_id', 'bag_name', 'duration_sec', 'ingested_at',
       'metadata.task_context.skill_code', 'metadata.task_context.skill_id',
       'metadata.task_context.skill_name',
       'metadata.task_context.operator_code',
       'metadata.task_context.operator_id',
       'metadata.technical_report.quality_gate.is_valid',
       ...
       'metadata.technical_report.topics./camera_r/depth/camera_info.status',
       'metadata.technical_report.topics./tf.status',
       'metadata.technical_report.topics./camera_fisheye_l/color/camera_info.status',
       'metadata.technical_report.topics./camera_fisheye_r/ffmpeg.status',
       'metadata.technical_report.topics./camera_l/depth/camera_info.status',
       'metadata.technical_report.topics./camera_l/depth/image_rect_raw.status',
       'metadata.technical_report.topics./camera_r/ffmpeg.status',
       'metadata.technical_report.topics./camera_fisheye_l/ffmpeg.status',
       'metadata.technical_report.topics./camera_l/ffmpeg.status',
       'metadata.technical_report.topics./gripper_l/data.status'],
      dtype='str', length=339)

In [20]:
data['recorded_at']

0       2026-01-30T09:41:14.964Z
1       2026-01-30T09:52:37.694Z
2       2026-01-30T09:57:36.119Z
3       2026-01-30T10:02:15.931Z
4       2026-01-30T10:13:54.732Z
                  ...
8828    2026-03-03T08:58:20.636Z
8829    2026-03-03T08:49:21.844Z
8830    2026-03-03T09:05:40.577Z
8831    2026-03-03T09:10:43.196Z
8832    2026-03-03T09:06:11.804Z
Name: recorded_at, Length: 8833, dtype: str

In [ ]:
data['metadata.task_context.skill_name']

0         d_vargas
1         d_vargas
2         d_vargas
3         d_vargas
4         d_vargas
           ...
8828    l_aguilera
8829      d_vargas
8830     c_becerra
8831     c_becerra
8832     e_cabezas
Name: metadata.task_context.operator_code, Length: 8833, dtype: str

In [26]:
column_name_map = {
    'duration_sec': 'Duration(s)',
    'recorded_at': 'StartTime',
    'metadata.task_context.operator_code': 'Operator',
    'metadata.technical_report.quality_gate.is_valid': 'IsValid',
    'metadata.technical_report.quality_gate.reason':'Reason',
    'station_id': 'Station'
}

data = data[list(column_name_map.keys())]

In [25]:
list(column_name_map.keys())

['duration_sec',
 'recorded_at',
 'metadata.task_context.operator_code',
 'metadata.technical_report.quality_gate.is_valid',
 'metadata.technical_report.quality_gate.reason',
 'station_id']

In [28]:
data.rename(columns=column_name_map)

,Duration(s),StartTime,Operator,IsValid,Reason,Station
0,542.804108,2026-01-30T09:41:14.964Z,d_vargas,False,MISSING_CRIT /camera_fisheye_r/ffmpeg | MISSIN...,1
1,199.397428,2026-01-30T09:52:37.694Z,d_vargas,False,MISSING_CRIT /camera_l/ffmpeg | MISSING_CRIT /...,1
2,208.702662,2026-01-30T09:57:36.119Z,d_vargas,False,BAD_HZ /gripper_l/data (98.2/120.0) | MISSING_...,1
3,140.026791,2026-01-30T10:02:15.931Z,d_vargas,False,MISSING_CRIT /camera_fisheye_l/ffmpeg | MISSIN...,1
4,174.669831,2026-01-30T10:13:54.732Z,d_vargas,False,MISSING_CRIT /camera_fisheye_l/ffmpeg | MISSIN...,1
...,...,...,...,...,...,...
8828,50.946379,2026-03-03T08:58:20.636Z,l_aguilera,False,TOO_SHORT (50.9s < 90.0s),4
8829,605.938992,2026-03-03T08:49:21.844Z,d_vargas,True,NaN,3
8830,255.516448,2026-03-03T09:05:40.577Z,c_becerra,True,NaN,2
8831,96.995837,2026-03-03T09:10:43.196Z,c_becerra,True,NaN,2
8832,600.092522,2026-03-03T09:06:11.804Z,e_cabezas,True,NaN,4

In [2]:
data['StartTime'] = pd.to_datetime(data['StartTime'])

In [ ]:
n= data['StartTime'].nunique()//6
j= data['StartTime'].nunique()%6

In [6]:
n

8

In [7]:
j

0

In [10]:
dates = data['StartTime'].unique()

In [11]:
dates[:-j]

array([], dtype=object)

In [12]:
import numpy as np
np.split(dates,n)

[array([datetime.date(2026, 1, 30), datetime.date(2026, 2, 2),
        datetime.date(2026, 2, 3), datetime.date(2026, 2, 4),
        datetime.date(2026, 2, 5), datetime.date(2026, 2, 6)], dtype=object),
 array([datetime.date(2026, 2, 7), datetime.date(2026, 1, 13),
        datetime.date(2026, 1, 14), datetime.date(2026, 1, 15),
        datetime.date(2026, 2, 9), datetime.date(2026, 1, 16)],
       dtype=object),
 array([datetime.date(2026, 1, 17), datetime.date(2026, 1, 19),
        datetime.date(2026, 1, 20), datetime.date(2026, 1, 21),
        datetime.date(2026, 2, 10), datetime.date(2026, 1, 22)],
       dtype=object),
 array([datetime.date(2026, 2, 11), datetime.date(2026, 1, 23),
        datetime.date(2026, 2, 12), datetime.date(2026, 1, 24),
        datetime.date(2026, 1, 26), datetime.date(2026, 1, 27)],
       dtype=object),
 array([datetime.date(2026, 1, 28), datetime.date(2026, 1, 29),
        datetime.date(2026, 2, 13), datetime.date(2026, 2, 14),
        datetime.date(2026, 1, 31), datetime.date(2026, 2, 16)],
       dtype=object),
 array([datetime.date(2026, 2, 17), datetime.date(2026, 2, 18),
        datetime.date(2026, 2, 19), datetime.date(2026, 2, 20),
        datetime.date(2026, 2, 21), datetime.date(2026, 2, 22)],
       dtype=object),
 array([datetime.date(2026, 2, 24), datetime.date(2026, 2, 25),
        datetime.date(2026, 2, 26), datetime.date(2026, 2, 27),
        datetime.date(2026, 2, 28), datetime.date(2026, 3, 2)],
       dtype=object),
 array([datetime.date(2026, 3, 3), datetime.date(2026, 3, 4),
        datetime.date(2026, 3, 5), datetime.date(2026, 3, 6),
        datetime.date(2026, 3, 7), datetime.date(2026, 3, 9)], dtype=object)]

In [15]:
data = data.sort_values(by='StartTime')

In [16]:
data['StartTime'].unique()

array([datetime.date(2026, 1, 13), datetime.date(2026, 1, 14),
       datetime.date(2026, 1, 15), datetime.date(2026, 1, 16),
       datetime.date(2026, 1, 17), datetime.date(2026, 1, 19),
       datetime.date(2026, 1, 20), datetime.date(2026, 1, 21),
       datetime.date(2026, 1, 22), datetime.date(2026, 1, 23),
       datetime.date(2026, 1, 24), datetime.date(2026, 1, 26),
       datetime.date(2026, 1, 27), datetime.date(2026, 1, 28),
       datetime.date(2026, 1, 29), datetime.date(2026, 1, 30),
       datetime.date(2026, 1, 31), datetime.date(2026, 2, 2),
       datetime.date(2026, 2, 3), datetime.date(2026, 2, 4),
       datetime.date(2026, 2, 5), datetime.date(2026, 2, 6),
       datetime.date(2026, 2, 7), datetime.date(2026, 2, 9),
       datetime.date(2026, 2, 10), datetime.date(2026, 2, 11),
       datetime.date(2026, 2, 12), datetime.date(2026, 2, 13),
       datetime.date(2026, 2, 14), datetime.date(2026, 2, 16),
       datetime.date(2026, 2, 17), datetime.date(2026, 2, 18),
       datetime.date(2026, 2, 19), datetime.date(2026, 2, 20),
       datetime.date(2026, 2, 21), datetime.date(2026, 2, 22),
       datetime.date(2026, 2, 24), datetime.date(2026, 2, 25),
       datetime.date(2026, 2, 26), datetime.date(2026, 2, 27),
       datetime.date(2026, 2, 28), datetime.date(2026, 3, 2),
       datetime.date(2026, 3, 3), datetime.date(2026, 3, 4),
       datetime.date(2026, 3, 5), datetime.date(2026, 3, 6),
       datetime.date(2026, 3, 7), datetime.date(2026, 3, 9)], dtype=object)

In [ ]:
import numpy as np
def weekly_data(df, w):

    df = df.sort_values(by='StartTime')
    weeks= df['StartTime'].dt.date.nunique()//6
    excess = df['StartTime'].dt.date.nunique()%6

    dates = df['StartTime'].dt.date.unique()

    f_dates = np.split(dates[:-excess],weeks)
    nef_dates = dates[-excess:]
    print(nef_dates)

    week = np.zeros(len(df))
    
    df['week'] = week

    counter = 1
    for chunk in f_dates:
        for date in chunk:
            for idx in range(len(df)):
                entry = df.loc[idx]
                if entry['StartTime'].date() == date:
                    print('daaa')
                    df.loc[idx,'week'] = counter
        counter += 1

    for date in nef_dates:
        for idx in range(len(df)):
            entry = df.loc[idx]
            if entry['StartTime'].date() == date:
                df.loc[idx,'week'] = counter

    week_db = df #[df['week']==w]

    return week_db

In [14]:
d = weekly_data(data,3)

In [ ]:
d

,Duration(s),StartTime,Operator,IsValid,FailReason,Station,SkillName,week
671,330.168232,2026-01-13 14:03:23.566000+00:00,e_martinez,True,MISSING_CRIT /camera_l/depth/image_rect_raw | ...,1,Organize beads per color,9.0
694,320.654732,2026-01-13 14:03:30.121000+00:00,c_becerra,True,MISSING_CRIT /camera_fisheye_l/ffmpeg | MISSIN...,2,Organize beads per color,9.0
705,361.051159,2026-01-13 14:10:34.577000+00:00,c_becerra,True,MISSING_CRIT /camera_l/ffmpeg | MISSING_CRIT /...,2,Put pasta in jars,9.0
686,161.108026,2026-01-13 14:10:42.729000+00:00,e_martinez,True,MISSING_CRIT /camera_fisheye_r/ffmpeg | MISSIN...,1,Put pasta in jars,9.0
684,87.789878,2026-01-13 14:23:11.720000+00:00,e_martinez,False,TOO_SHORT (87.8s < 90.0s) | MISSING_CRIT /came...,1,Insert allen keys in package,9.0
...,...,...,...,...,...,...,...,...
10074,121.992821,2026-03-09 07:56:07.123000+00:00,c_becerra,True,NaN,1,Build Up Box (Mailer),9.0
10076,266.007577,2026-03-09 07:57:05.087000+00:00,l_aguilera,True,NaN,3,Put pasta in ziploc bags,9.0
10075,90.767251,2026-03-09 07:58:27.884000+00:00,c_becerra,True,NaN,1,Build Up Box (Mailer),9.0
10078,96.673562,2026-03-09 08:06:47.632000+00:00,l_aguilera,True,NaN,3,Built up box (Present),9.0
10079,95.630602,2026-03-09 08:09:00.754000+00:00,l_aguilera,True,NaN,3,Built up box (Present),9.0